# JSON

## Introduction

In this lecture, you'll continue investigating new formats for data. Specifically, you'll investigate one of the most popular data formats for the web: JSON files.

## Objectives
You will be able to:
* Use the JSON module to load and parse JSON documents


## JSON

JSON stands for JavaScript Object Notation. When it was first introduced, JSON files were meant to streamline many data transportation issues at the time. It is now the common standard amongst data transfers on the web and has numerous parsing packages for numerous languages (including Python)! 

Here's a brief preview of a JSON file:  

<img src="images/json_preview.png" width="850">

## Loading JSON Data

Prebuilt Python modules exist that will give you a powerful starting point for accessing and manipulating the underlying data in JSON files. We will work with the `json` module.

### The JSON Module

https://docs.python.org/3.6/library/json.html

In [1]:
import json

To load a json file, you first open the file using python's built-in function and then pass that file object to the json module's load method. As you can see, this loaded the data as a dictionary.

In [2]:
f = open('nyc_2001_campaign_finance.json')
data = json.load(f)
print(type(data))

<class 'dict'>

Json files are often nested in a hierarchical structure and will have data structures analogous to python dictionaries and lists. You can begin to investigate a particular file by using our traditional python methods. Here's all of the built-in supported data types in JSON and their counterparts in python: 

<img src="images/json_python_datatypes.png" width=500>

Check the keys of the dictionary:

In [3]:
data.keys()

dict_keys(['meta', 'data'])

Investigate what data types are stored within the values associated with those keys:

In [4]:
for v in data.values():
    print(type(v))

<class 'dict'>
<class 'list'>

You can quickly preview the first dictionary as a DataFrame

In [6]:
import pandas as pd

In [7]:
pd.DataFrame.from_dict(data['meta'])

                                                                       view
attribution                                    Campaign Finance Board (CFB)
averageRating                                                             0
category                                                    City Government
columns                   [{'id': -1, 'name': 'sid', 'dataTypeName': 'me...
createdAt                                                        1315950830
description               A listing of public funds payments for candida...
displayType                                                           table
downloadCount                                                          1470
flags                         [default, restorable, restorePossibleForType]
grants                    [{'inherited': False, 'type': 'viewer', 'flags...
hideFromCatalog                                                       False
hideFromDataJson                                                      False
id                                                                8dhd-zvi6
indexUpdatedAt                                                   1536596254
metadata                  {'rdfSubject': '0', 'rdfClass': '', 'attachmen...
name                                                 2001 Campaign Payments
newBackend                                                            False
numberOfComments                                                          0
oid                                                                 4140996
owner                     {'id': '5fuc-pqz2', 'displayName': 'NYC OpenDa...
provenance                                                         official
publicationAppendEnabled                                              False
publicationDate                                                  1371845179
publicationGroup                                                     240370
publicationStage                                                  published
query                                                                    {}
rights                                                               [read]
rowClass
rowsUpdatedAt                                                    1371845177
rowsUpdatedBy                                                     5fuc-pqz2
tableAuthor               {'id': '5fuc-pqz2', 'displayName': 'NYC OpenDa...
tableId                                                              932968
tags                      [finance, campaign finance board, cfb, nyccfb,...
totalTimesRated                                                           0
viewCount                                                               233
viewLastModified                                                 1536605717
viewType                                                            tabular

Notice the column names which will be very useful!

Investigate further information about the list stored under the 'data' key:

In [8]:
len(data['data'])

285

Previewing the first entry:

In [9]:
data['data'][0]

[1,
 'E3E9CC9F-7443-43F6-94AF-B5A0F802DBA1',
 1,
 1315925633,
 '392904',
 1315925633,
 '392904',
 '{\n  "invalidCells" : {\n    "1519001" : "TOTALPAY",\n    "1518998" : "PRIMARYPAY",\n    "1519000" : "RUNOFFPAY",\n    "1518999" : "GENERALPAY",\n    "1518994" : "OFFICECD",\n    "1518996" : "OFFICEDIST",\n    "1518991" : "ELECTION"\n  }\n}',
 None,
 'CANDID',
 'CANDNAME',
 None,
 'OFFICEBORO',
 None,
 'CANCLASS',
 None,
 None,
 None,
 None]

In [10]:
pd.DataFrame.from_dict(data['data'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,E3E9CC9F-7443-43F6-94AF-B5A0F802DBA1,1,1315925633,392904,1315925633,392904,"{\n ""invalidCells"" : {\n ""1519001"" : ""TOTA...",None,CANDID,CANDNAME,None,OFFICEBORO,None,CANCLASS,None,None,None,None
1,2,9D257416-581A-4C42-85CC-B6EAD9DED97F,2,1315925633,392904,1315925633,392904,{\n},2001,B4,"Aboulafia, Sandy",5,None,44,P,45410.00,0,0,45410.00
2,3,B80D7891-93CF-49E8-86E8-182B618E68F2,3,1315925633,392904,1315925633,392904,{\n},2001,445,"Adams, Jackie R",5,None,7,P,11073.00,0,0,11073.00
3,4,BB012003-78F5-406D-8A87-7FF8A425EE3F,4,1315925633,392904,1315925633,392904,{\n},2001,HF,"Addabbo, Joseph P",5,None,32,P,75350.00,73970.00,0,149320.00
4,5,945825F9-2F5D-47C2-A16B-75B93E61E1AD,5,1315925633,392904,1315925633,392904,{\n},2001,IR,"Alamo-Estrada, Agustin",5,None,14,P,25000.00,2400.00,0,27400.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,281,C50E6A4C-BDE9-4F12-97F4-95D467013540,281,1315925633,392904,1315925633,392904,{\n},2001,537,"Wilson, John H",5,None,13,P,0,0,0,0
281,282,04C6D19F-FF63-47B0-B26D-3B8F98B4C16B,282,1315925633,392904,1315925633,392904,{\n},2001,559,"Wooten, Donald T",5,None,42,P,0,0,0,0
282,283,A451E0E9-D382-4A97-AAD8-D7D382055F8D,283,1315925633,392904,1315925633,392904,{\n},2001,280,"Yassky, David",5,None,33,P,75350.00,75350.00,0,150700.00
283,284,E84BCD0C-D6F4-450F-B55B-3199A265C781,284,1315925633,392904,1315925633,392904,{\n},2001,274,"Zapiti, Mike",5,None,22,P,12172.00,0,0,12172.00
284,285,5BBC9676-2119-4FB5-9DAB-DE3F71B7681A,285,1315925633,392904,1315925633,392904,{\n},2001,442,"Zett, Lori M",5,None,24,P,0,0,0,0

## Summary
As you can see, there's still a lot going on here with the deeply nested structure of JSON data files. In the upcoming lab, you'll get a chance to practice loading files and conducting some initial preview of the data as you did here.